replicaCount: 1

image:                                                                 
  repository: ${TF_OUT_server_ecr_url}
  # set pullPolicy to always for tight test cycles bypassing CI
  pullPolicy: Always
  tag: "latest"                                                              

service:
  port: 50051

ray:
  serviceName: ${TF_OUT_ray_service}

rpdbPort: 4444

resources:
  limits:
    cpu: 100m
    memory: 512Mi 
  requests:
    cpu: 100m
    memory: 512Mi

