replicaCount: 1

image:                                                                 
  repository: ${IMAGE_REPOSITORY}
  # set pullPolicy to always for tight test cycles bypassing CI
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.     
  tag: "latest"                                                              

service:
  type: ClusterIP
  port: 50051

resources:
  limits:
    cpu: 100m
    memory: 512Mi 
  requests:
    cpu: 100m
    memory: 512Mi

