replicaCount: 1

image:                                                                 
  repository: ${IMAGE_REPOSITORY}
  # set pullPolicy to always for tight test cycles bypassing CI
  pullPolicy: Always
  tag: "latest"                                                              

service:
  port: 50051

resources:
  limits:
    cpu: 100m
    memory: 512Mi 
  requests:
    cpu: 100m
    memory: 512Mi

cluster-autoscaler:
  enabled: true
  autoDiscovery:
    clusterName: ${CLUSTER_NAME}



