{{- $fullName := include "deploy.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: default
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  defaultBackend:
    service:
      name: {{ include "deploy.fullname" . }}
      port:
        number: {{ .Values.service.port }}
