apiVersion: v1
kind: Service
metadata:
  name: {{ include "deploy.fullname" . }}
  namespace: default
  labels:
    {{- include "deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "deploy.selectorLabels" . | nindent 4 }}
