#!/bin/env bash

set -o pipefail
set -o errexit
set -o nounset
set -o xtrace

# install protobuf extensions for go
go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

# install python development-time deps
python -m venv venv
venv/bin/python -m pip install -r requirements.txt

